### ISSUE TITLE
Possible Typo in Documentation

### ISSUE THREAD

**Issue by bytesource** [pimbrouwers/Falco.Markup#1]
Hi Pim, 

In the documentation about Falco. Markup, https://www.falcoframework.com/docs/markup.html, I found a possible typo. In this code example (HTML ⇒ Merging Attributes):

``` fsharp
// Template
let master (title : string) (content : XmlNode list) =
    Elem.html [ Attr.lang "en" ] [
        Elem.head [] [
            Elem.title [] [ Text.raw "Sample App" ]
        ]
        Elem.body [] content
    ]
```
`[ Text.raw "Sample App" ]` should probably be `[ Text.raw title ]`.

**Comment by pimbrouwers** [comment]
Hey! Thanks for spotting this! Will correct!

**Comment by bytesource** [comment]
Hi Pim, 

I just finished reading the documentation. Falco has such a beautiful and consistent API, I really like it!

I hope you don't mind listing a few other places that might have a typo:

1) https://www.falcoframework.com/docs/markup.html
**HTML => Merging Attributes**

``` fsharp
// Template
let master (title : string) (content : XmlNode list) =
    Elem.html [ Attr.lang "en" ] [
        Elem.head [] [
            Elem.title [] [ Text.raw "Sample App" ]
        ]
        Elem.body [] content
    ]
```
This is the same code example I mentioned yesterday. 

2) https://www.falcoframework.com/docs/host.html#host
**Custom Services and Middleware => add_service**

`let connectToDb : HttpHandler =`

This function doesn't have a body. At least to me, it looks like that.

3) 
![image](https://user-images.githubusercontent.com/610307/193497031-f296a2eb-74df-4962-9b6f-ebdb6e6bcaa5.png)

For these links, the jump link doesn't work and the section “Other Operations” doesn't exist.

Keep up the good work!

Stefan

**Comment by pimbrouwers** [comment]
Reference: https://github.com/pimbrouwers/Falco/issues/100
