### ISSUE TITLE
Falco.Markup documentation is wrong

### ISSUE THREAD

**Issue by pkese** [pimbrouwers/Falco.Markup#2]
At the beginning of [Markup page](https://www.falcoframework.com/docs/markup.html) user is pointed to `Falco.Markup v1.0.1` nuget package.

![image](https://user-images.githubusercontent.com/278492/199054802-397c5781-92d8-47fb-b79e-02942e7176c7.png)

However once installed, the compiler starts complaining that Falco.Markup v1.0.1. is not compatible with Falco 3.1.14.

Apparently the correct thing to do is to NOT install Falco.Markup, as Markup comes with base Falco install.

So maybe it would be better to not direct people to a separate Falco.Markup package, or make the distinction between Falco and Falco.Markup clearer.

**Comment by pkese** [comment]
This should actually be reported under Falco, not Falco.Markup as it relates to Falco docs.

**Comment by pkese** [comment]
Also if https://www.falcoframework.com/docs/response.html#html-responses demo code would start with the name of the module that needs to be open in order to get `Elem.html`

```fsharp
open Falco.Markup
```
... then, that would make it much easier for people to get started without shooting themselves into the foot.

**Comment by pimbrouwers** [comment]
See: https://github.com/pimbrouwers/Falco/issues/87#issuecomment-1277491460
