### ISSUE TITLE
Javascript events are missing "on" prefix

### ISSUE THREAD

**Issue by MaciekWin3** [pimbrouwers/Falco.Markup#3]
Hi, I recently istarted learning F# and discover Falco, which I' am really enjoying. One issue that I dicovered with markup module that HTML that is generated by Attr module is not correct. It's missing 'on' prefix. For example code:
``` 
let doc =
    Elem.html [] [
        Elem.body [ Attr.class' "100-vh" ] [
            Elem.button [ Attr.onclick "sayHello()" ] [ Text.raw "Click me" ]
        ]
        Elem.script [] [ Text.raw """
                function sayHello() {
                    console.log("hello world")
                }
            """]
    ]
```
generates html like this: 
```
<!DOCTYPE html>
<html>
  <body class="100-vh">
    <button click="sayHello()">Click me</button>
  </body>
  <script>
    function sayHello() {
      console.log("hello world");
    }
  </script>
</html>
```
Everthing is correct except button won't work because Falco translates Attr.onclick to 'click' insted of 'onclick'. I see this is the case not only for onclick but also for ondblclick, ondrag and so on.

**Comment by MaciekWin3** [comment]
I created PR for this: https://github.com/pimbrouwers/Falco.Markup/pulls

**Comment by pimbrouwers** [comment]
Oh dear god...

Thank you very much for catching this!

**Comment by pimbrouwers** [comment]
Reference: #4
