### ISSUE TITLE
Html beautifier

### ISSUE THREAD

**Issue by melursus23** [pimbrouwers/Falco.Markup#5]
Hello,

Is there an option for the generated HTML to look prettier? 
Right now, it's a big long line. 
So when I'm trying to debug, it's hard to read and I'm using a HTML beautifier to understand and troubleshoot it.
However, that make is a little bit harder since it's one extra step each time.

Thanks

**Comment by pimbrouwers** [comment]
I apologize for the immense delay on this issue. 

Currently we only support fully serialized output (i.e., minified). Without changing the API, or adding a global configuration variable, neither of which I'm too keen on. I don't see how we could achieve this.

Luckily the browser inspector does this for us! So I would recommend using either Chrome or Firefox's inspector to make debugging easier.

Cheers!
